name: "Terraform Plan Pagamento"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]
    paths: ["pagamento/**", ".github/workflows/ci-terraform-plan-pagamento-infra-main.yaml"]
  workflow_dispatch:

env:
  TF_VAR_db_pagamento_user: ${{ secrets.TF_VAR_DB_PAGAMENTO_USER }}
  TF_VAR_db_pagamento_user_password: ${{ secrets.TF_VAR_DB_PAGAMENTO_USER_PASSWORD }}

jobs: 
  terraform:
    name: "Terraform Plan Pagamento"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Google auth
        id: auth
        uses: google-github-actions/auth@v2.0.0  
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform init
        working-directory: ./pagamento
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: ./pagamento
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
